exclude: [CNAME, CONTRIBUTING.md, Gemfile, Gemfile.lock, LICENSE, README.md, script, TRANSLATION_REFERENCE.md, vendor]
collections:
  pages:
    output: true
    permalink: /:categories/:title:output_ext
