name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  jekyll:
    name: Run Jekyll Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true
    - run: script/run_jekyll.sh
  validate-json:
    name: Validate JSON
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true
    - run: script/validate_json.rb
  ping-websites:
    name: Ping Websites
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true
    - run: script/ping_websites.rb
  check-files-formatting:
    name: Check Files Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true
    - run: script/check_files_formatting.sh
